apiVersion: v1
kind: Service
metadata:
  name: e-store-service
spec:
  selector:
    app: e-store
  ports:
    - protocol: TCP
      port: 5000        # Port exposed by the service
      targetPort: 5000  # Port on the container
  type: NodePort
